server:
  port: 8781

spring:
  #项目名称
  application:
    name: rq_house_server
  #数据源
  datasource:
    url: jdbc:mysql://localhost:3306/ruiqinbus?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  #整合redis  孩子  你本地安装了redis了吗？ 没有就注释了吧
  redis:
    database: 0
    host: localhost
    port: 6379
    timeout: 2000



#  触发器热部署
  devtools:
    restart:
      trigger-file: trigger.txt

#  控制台打印sql
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

## 服务端eureka 地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

rq-user-server:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.WeightedResponseTimeRule


#开启feign
feign:
  hystrix:
    enabled: true




